version: "3.9"
services:
  api:
    build: ../services/ingest_worker
    env_file: ../.env
    ports: ["8000:8000"]
    depends_on: [qdrant, redis]
  qdrant:
    image: qdrant/qdrant:v1.8.3
    ports: ["6333:6333"]
    volumes: ["../qdrant_storage:/qdrant/storage"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  n8n:
    image: n8nio/n8n:latest
    ports: ["5678:5678"]
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
    volumes:
      - ../n8n/flows:/data
